// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FailedMemberInfo.proto

package proto;

public final class FailedMemberInfo {
  private FailedMemberInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FailedMemberInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.FailedMemberInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestSenderType = 1;</code>
     * @return The requestSenderType.
     */
    java.lang.String getRequestSenderType();
    /**
     * <code>string requestSenderType = 1;</code>
     * @return The bytes for requestSenderType.
     */
    com.google.protobuf.ByteString
        getRequestSenderTypeBytes();

    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @return A list containing the failedBrokerId.
     */
    java.util.List<java.lang.Integer> getFailedBrokerIdList();
    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @return The count of failedBrokerId.
     */
    int getFailedBrokerIdCount();
    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @param index The index of the element to return.
     * @return The failedBrokerId at the given index.
     */
    int getFailedBrokerId(int index);
  }
  /**
   * Protobuf type {@code tutorial.FailedMemberInfoDetails}
   */
  public static final class FailedMemberInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.FailedMemberInfoDetails)
      FailedMemberInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FailedMemberInfoDetails.newBuilder() to construct.
    private FailedMemberInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FailedMemberInfoDetails() {
      requestSenderType_ = "";
      failedBrokerId_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FailedMemberInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FailedMemberInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestSenderType_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                failedBrokerId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              failedBrokerId_.addInt(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                failedBrokerId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                failedBrokerId_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          failedBrokerId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.FailedMemberInfo.internal_static_tutorial_FailedMemberInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.FailedMemberInfo.internal_static_tutorial_FailedMemberInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FailedMemberInfo.FailedMemberInfoDetails.class, proto.FailedMemberInfo.FailedMemberInfoDetails.Builder.class);
    }

    public static final int REQUESTSENDERTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestSenderType_;
    /**
     * <code>string requestSenderType = 1;</code>
     * @return The requestSenderType.
     */
    @java.lang.Override
    public java.lang.String getRequestSenderType() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestSenderType_ = s;
        return s;
      }
    }
    /**
     * <code>string requestSenderType = 1;</code>
     * @return The bytes for requestSenderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestSenderTypeBytes() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestSenderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAILEDBROKERID_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList failedBrokerId_;
    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @return A list containing the failedBrokerId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getFailedBrokerIdList() {
      return failedBrokerId_;
    }
    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @return The count of failedBrokerId.
     */
    public int getFailedBrokerIdCount() {
      return failedBrokerId_.size();
    }
    /**
     * <code>repeated uint32 failedBrokerId = 2;</code>
     * @param index The index of the element to return.
     * @return The failedBrokerId at the given index.
     */
    public int getFailedBrokerId(int index) {
      return failedBrokerId_.getInt(index);
    }
    private int failedBrokerIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestSenderType_);
      }
      if (getFailedBrokerIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(failedBrokerIdMemoizedSerializedSize);
      }
      for (int i = 0; i < failedBrokerId_.size(); i++) {
        output.writeUInt32NoTag(failedBrokerId_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestSenderType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < failedBrokerId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(failedBrokerId_.getInt(i));
        }
        size += dataSize;
        if (!getFailedBrokerIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        failedBrokerIdMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.FailedMemberInfo.FailedMemberInfoDetails)) {
        return super.equals(obj);
      }
      proto.FailedMemberInfo.FailedMemberInfoDetails other = (proto.FailedMemberInfo.FailedMemberInfoDetails) obj;

      if (!getRequestSenderType()
          .equals(other.getRequestSenderType())) return false;
      if (!getFailedBrokerIdList()
          .equals(other.getFailedBrokerIdList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTSENDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestSenderType().hashCode();
      if (getFailedBrokerIdCount() > 0) {
        hash = (37 * hash) + FAILEDBROKERID_FIELD_NUMBER;
        hash = (53 * hash) + getFailedBrokerIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FailedMemberInfo.FailedMemberInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.FailedMemberInfo.FailedMemberInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.FailedMemberInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.FailedMemberInfoDetails)
        proto.FailedMemberInfo.FailedMemberInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.FailedMemberInfo.internal_static_tutorial_FailedMemberInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.FailedMemberInfo.internal_static_tutorial_FailedMemberInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.FailedMemberInfo.FailedMemberInfoDetails.class, proto.FailedMemberInfo.FailedMemberInfoDetails.Builder.class);
      }

      // Construct using proto.FailedMemberInfo.FailedMemberInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestSenderType_ = "";

        failedBrokerId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.FailedMemberInfo.internal_static_tutorial_FailedMemberInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.FailedMemberInfo.FailedMemberInfoDetails getDefaultInstanceForType() {
        return proto.FailedMemberInfo.FailedMemberInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.FailedMemberInfo.FailedMemberInfoDetails build() {
        proto.FailedMemberInfo.FailedMemberInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.FailedMemberInfo.FailedMemberInfoDetails buildPartial() {
        proto.FailedMemberInfo.FailedMemberInfoDetails result = new proto.FailedMemberInfo.FailedMemberInfoDetails(this);
        int from_bitField0_ = bitField0_;
        result.requestSenderType_ = requestSenderType_;
        if (((bitField0_ & 0x00000001) != 0)) {
          failedBrokerId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.failedBrokerId_ = failedBrokerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.FailedMemberInfo.FailedMemberInfoDetails) {
          return mergeFrom((proto.FailedMemberInfo.FailedMemberInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.FailedMemberInfo.FailedMemberInfoDetails other) {
        if (other == proto.FailedMemberInfo.FailedMemberInfoDetails.getDefaultInstance()) return this;
        if (!other.getRequestSenderType().isEmpty()) {
          requestSenderType_ = other.requestSenderType_;
          onChanged();
        }
        if (!other.failedBrokerId_.isEmpty()) {
          if (failedBrokerId_.isEmpty()) {
            failedBrokerId_ = other.failedBrokerId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFailedBrokerIdIsMutable();
            failedBrokerId_.addAll(other.failedBrokerId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.FailedMemberInfo.FailedMemberInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.FailedMemberInfo.FailedMemberInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestSenderType_ = "";
      /**
       * <code>string requestSenderType = 1;</code>
       * @return The requestSenderType.
       */
      public java.lang.String getRequestSenderType() {
        java.lang.Object ref = requestSenderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestSenderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestSenderType = 1;</code>
       * @return The bytes for requestSenderType.
       */
      public com.google.protobuf.ByteString
          getRequestSenderTypeBytes() {
        java.lang.Object ref = requestSenderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestSenderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestSenderType = 1;</code>
       * @param value The requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestSenderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSenderType() {
        
        requestSenderType_ = getDefaultInstance().getRequestSenderType();
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 1;</code>
       * @param value The bytes for requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestSenderType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList failedBrokerId_ = emptyIntList();
      private void ensureFailedBrokerIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          failedBrokerId_ = mutableCopy(failedBrokerId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @return A list containing the failedBrokerId.
       */
      public java.util.List<java.lang.Integer>
          getFailedBrokerIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(failedBrokerId_) : failedBrokerId_;
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @return The count of failedBrokerId.
       */
      public int getFailedBrokerIdCount() {
        return failedBrokerId_.size();
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @param index The index of the element to return.
       * @return The failedBrokerId at the given index.
       */
      public int getFailedBrokerId(int index) {
        return failedBrokerId_.getInt(index);
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @param index The index to set the value at.
       * @param value The failedBrokerId to set.
       * @return This builder for chaining.
       */
      public Builder setFailedBrokerId(
          int index, int value) {
        ensureFailedBrokerIdIsMutable();
        failedBrokerId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @param value The failedBrokerId to add.
       * @return This builder for chaining.
       */
      public Builder addFailedBrokerId(int value) {
        ensureFailedBrokerIdIsMutable();
        failedBrokerId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @param values The failedBrokerId to add.
       * @return This builder for chaining.
       */
      public Builder addAllFailedBrokerId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFailedBrokerIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, failedBrokerId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 failedBrokerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFailedBrokerId() {
        failedBrokerId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.FailedMemberInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.FailedMemberInfoDetails)
    private static final proto.FailedMemberInfo.FailedMemberInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.FailedMemberInfo.FailedMemberInfoDetails();
    }

    public static proto.FailedMemberInfo.FailedMemberInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FailedMemberInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<FailedMemberInfoDetails>() {
      @java.lang.Override
      public FailedMemberInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FailedMemberInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FailedMemberInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FailedMemberInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.FailedMemberInfo.FailedMemberInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_FailedMemberInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_FailedMemberInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026FailedMemberInfo.proto\022\010tutorial\"L\n\027Fa" +
      "iledMemberInfoDetails\022\031\n\021requestSenderTy" +
      "pe\030\001 \001(\t\022\026\n\016failedBrokerId\030\002 \003(\rB\031\n\005prot" +
      "oB\020FailedMemberInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_FailedMemberInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_FailedMemberInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_FailedMemberInfoDetails_descriptor,
        new java.lang.String[] { "RequestSenderType", "FailedBrokerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
