// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MembersInfo.proto

package proto;

public final class MembersInfo {
  private MembersInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MembersInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.MembersInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 memberId = 1;</code>
     * @return The memberId.
     */
    int getMemberId();

    /**
     * <code>string memberName = 2;</code>
     * @return The memberName.
     */
    java.lang.String getMemberName();
    /**
     * <code>string memberName = 2;</code>
     * @return The bytes for memberName.
     */
    com.google.protobuf.ByteString
        getMemberNameBytes();

    /**
     * <code>string memberIP = 3;</code>
     * @return The memberIP.
     */
    java.lang.String getMemberIP();
    /**
     * <code>string memberIP = 3;</code>
     * @return The bytes for memberIP.
     */
    com.google.protobuf.ByteString
        getMemberIPBytes();

    /**
     * <code>int32 memberPort = 4;</code>
     * @return The memberPort.
     */
    int getMemberPort();
  }
  /**
   * Protobuf type {@code tutorial.MembersInfoDetails}
   */
  public static final class MembersInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.MembersInfoDetails)
      MembersInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MembersInfoDetails.newBuilder() to construct.
    private MembersInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MembersInfoDetails() {
      memberName_ = "";
      memberIP_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MembersInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MembersInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              memberId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              memberName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              memberIP_ = s;
              break;
            }
            case 32: {

              memberPort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.MembersInfo.internal_static_tutorial_MembersInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.MembersInfo.internal_static_tutorial_MembersInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.MembersInfo.MembersInfoDetails.class, proto.MembersInfo.MembersInfoDetails.Builder.class);
    }

    public static final int MEMBERID_FIELD_NUMBER = 1;
    private int memberId_;
    /**
     * <code>int32 memberId = 1;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public int getMemberId() {
      return memberId_;
    }

    public static final int MEMBERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object memberName_;
    /**
     * <code>string memberName = 2;</code>
     * @return The memberName.
     */
    @java.lang.Override
    public java.lang.String getMemberName() {
      java.lang.Object ref = memberName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberName_ = s;
        return s;
      }
    }
    /**
     * <code>string memberName = 2;</code>
     * @return The bytes for memberName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberNameBytes() {
      java.lang.Object ref = memberName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERIP_FIELD_NUMBER = 3;
    private volatile java.lang.Object memberIP_;
    /**
     * <code>string memberIP = 3;</code>
     * @return The memberIP.
     */
    @java.lang.Override
    public java.lang.String getMemberIP() {
      java.lang.Object ref = memberIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberIP_ = s;
        return s;
      }
    }
    /**
     * <code>string memberIP = 3;</code>
     * @return The bytes for memberIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberIPBytes() {
      java.lang.Object ref = memberIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERPORT_FIELD_NUMBER = 4;
    private int memberPort_;
    /**
     * <code>int32 memberPort = 4;</code>
     * @return The memberPort.
     */
    @java.lang.Override
    public int getMemberPort() {
      return memberPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (memberId_ != 0) {
        output.writeInt32(1, memberId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memberName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, memberName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memberIP_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, memberIP_);
      }
      if (memberPort_ != 0) {
        output.writeInt32(4, memberPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (memberId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, memberId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memberName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, memberName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memberIP_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, memberIP_);
      }
      if (memberPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, memberPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.MembersInfo.MembersInfoDetails)) {
        return super.equals(obj);
      }
      proto.MembersInfo.MembersInfoDetails other = (proto.MembersInfo.MembersInfoDetails) obj;

      if (getMemberId()
          != other.getMemberId()) return false;
      if (!getMemberName()
          .equals(other.getMemberName())) return false;
      if (!getMemberIP()
          .equals(other.getMemberIP())) return false;
      if (getMemberPort()
          != other.getMemberPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + getMemberId();
      hash = (37 * hash) + MEMBERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMemberName().hashCode();
      hash = (37 * hash) + MEMBERIP_FIELD_NUMBER;
      hash = (53 * hash) + getMemberIP().hashCode();
      hash = (37 * hash) + MEMBERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getMemberPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MembersInfo.MembersInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.MembersInfo.MembersInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MembersInfo.MembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.MembersInfo.MembersInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.MembersInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.MembersInfoDetails)
        proto.MembersInfo.MembersInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.MembersInfo.internal_static_tutorial_MembersInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.MembersInfo.internal_static_tutorial_MembersInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.MembersInfo.MembersInfoDetails.class, proto.MembersInfo.MembersInfoDetails.Builder.class);
      }

      // Construct using proto.MembersInfo.MembersInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        memberId_ = 0;

        memberName_ = "";

        memberIP_ = "";

        memberPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.MembersInfo.internal_static_tutorial_MembersInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.MembersInfo.MembersInfoDetails getDefaultInstanceForType() {
        return proto.MembersInfo.MembersInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.MembersInfo.MembersInfoDetails build() {
        proto.MembersInfo.MembersInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.MembersInfo.MembersInfoDetails buildPartial() {
        proto.MembersInfo.MembersInfoDetails result = new proto.MembersInfo.MembersInfoDetails(this);
        result.memberId_ = memberId_;
        result.memberName_ = memberName_;
        result.memberIP_ = memberIP_;
        result.memberPort_ = memberPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.MembersInfo.MembersInfoDetails) {
          return mergeFrom((proto.MembersInfo.MembersInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.MembersInfo.MembersInfoDetails other) {
        if (other == proto.MembersInfo.MembersInfoDetails.getDefaultInstance()) return this;
        if (other.getMemberId() != 0) {
          setMemberId(other.getMemberId());
        }
        if (!other.getMemberName().isEmpty()) {
          memberName_ = other.memberName_;
          onChanged();
        }
        if (!other.getMemberIP().isEmpty()) {
          memberIP_ = other.memberIP_;
          onChanged();
        }
        if (other.getMemberPort() != 0) {
          setMemberPort(other.getMemberPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.MembersInfo.MembersInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.MembersInfo.MembersInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int memberId_ ;
      /**
       * <code>int32 memberId = 1;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public int getMemberId() {
        return memberId_;
      }
      /**
       * <code>int32 memberId = 1;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(int value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memberId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        
        memberId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object memberName_ = "";
      /**
       * <code>string memberName = 2;</code>
       * @return The memberName.
       */
      public java.lang.String getMemberName() {
        java.lang.Object ref = memberName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memberName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string memberName = 2;</code>
       * @return The bytes for memberName.
       */
      public com.google.protobuf.ByteString
          getMemberNameBytes() {
        java.lang.Object ref = memberName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string memberName = 2;</code>
       * @param value The memberName to set.
       * @return This builder for chaining.
       */
      public Builder setMemberName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memberName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string memberName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberName() {
        
        memberName_ = getDefaultInstance().getMemberName();
        onChanged();
        return this;
      }
      /**
       * <code>string memberName = 2;</code>
       * @param value The bytes for memberName to set.
       * @return This builder for chaining.
       */
      public Builder setMemberNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memberName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object memberIP_ = "";
      /**
       * <code>string memberIP = 3;</code>
       * @return The memberIP.
       */
      public java.lang.String getMemberIP() {
        java.lang.Object ref = memberIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memberIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string memberIP = 3;</code>
       * @return The bytes for memberIP.
       */
      public com.google.protobuf.ByteString
          getMemberIPBytes() {
        java.lang.Object ref = memberIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string memberIP = 3;</code>
       * @param value The memberIP to set.
       * @return This builder for chaining.
       */
      public Builder setMemberIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memberIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string memberIP = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberIP() {
        
        memberIP_ = getDefaultInstance().getMemberIP();
        onChanged();
        return this;
      }
      /**
       * <code>string memberIP = 3;</code>
       * @param value The bytes for memberIP to set.
       * @return This builder for chaining.
       */
      public Builder setMemberIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memberIP_ = value;
        onChanged();
        return this;
      }

      private int memberPort_ ;
      /**
       * <code>int32 memberPort = 4;</code>
       * @return The memberPort.
       */
      @java.lang.Override
      public int getMemberPort() {
        return memberPort_;
      }
      /**
       * <code>int32 memberPort = 4;</code>
       * @param value The memberPort to set.
       * @return This builder for chaining.
       */
      public Builder setMemberPort(int value) {
        
        memberPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memberPort = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberPort() {
        
        memberPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.MembersInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.MembersInfoDetails)
    private static final proto.MembersInfo.MembersInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.MembersInfo.MembersInfoDetails();
    }

    public static proto.MembersInfo.MembersInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MembersInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<MembersInfoDetails>() {
      @java.lang.Override
      public MembersInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MembersInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MembersInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MembersInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.MembersInfo.MembersInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MembersInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_MembersInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MembersInfo.proto\022\010tutorial\"`\n\022Members" +
      "InfoDetails\022\020\n\010memberId\030\001 \001(\005\022\022\n\nmemberN" +
      "ame\030\002 \001(\t\022\020\n\010memberIP\030\003 \001(\t\022\022\n\nmemberPor" +
      "t\030\004 \001(\005B\024\n\005protoB\013MembersInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_MembersInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_MembersInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_MembersInfoDetails_descriptor,
        new java.lang.String[] { "MemberId", "MemberName", "MemberIP", "MemberPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
