// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicateSuccessACK.proto

package proto;

public final class ReplicateSuccessACK {
  private ReplicateSuccessACK() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReplicateSuccessACKDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ReplicateSuccessACKDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool synchronous = 1;</code>
     * @return The synchronous.
     */
    boolean getSynchronous();

    /**
     * <code>uint64 ackNum = 2;</code>
     * @return The ackNum.
     */
    long getAckNum();

    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();
  }
  /**
   * Protobuf type {@code tutorial.ReplicateSuccessACKDetails}
   */
  public static final class ReplicateSuccessACKDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ReplicateSuccessACKDetails)
      ReplicateSuccessACKDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReplicateSuccessACKDetails.newBuilder() to construct.
    private ReplicateSuccessACKDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplicateSuccessACKDetails() {
      topic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReplicateSuccessACKDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReplicateSuccessACKDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              synchronous_ = input.readBool();
              break;
            }
            case 16: {

              ackNum_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ReplicateSuccessACK.internal_static_tutorial_ReplicateSuccessACKDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ReplicateSuccessACK.internal_static_tutorial_ReplicateSuccessACKDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.class, proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.Builder.class);
    }

    public static final int SYNCHRONOUS_FIELD_NUMBER = 1;
    private boolean synchronous_;
    /**
     * <code>bool synchronous = 1;</code>
     * @return The synchronous.
     */
    @java.lang.Override
    public boolean getSynchronous() {
      return synchronous_;
    }

    public static final int ACKNUM_FIELD_NUMBER = 2;
    private long ackNum_;
    /**
     * <code>uint64 ackNum = 2;</code>
     * @return The ackNum.
     */
    @java.lang.Override
    public long getAckNum() {
      return ackNum_;
    }

    public static final int TOPIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (synchronous_ != false) {
        output.writeBool(1, synchronous_);
      }
      if (ackNum_ != 0L) {
        output.writeUInt64(2, ackNum_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (synchronous_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, synchronous_);
      }
      if (ackNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, ackNum_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ReplicateSuccessACK.ReplicateSuccessACKDetails)) {
        return super.equals(obj);
      }
      proto.ReplicateSuccessACK.ReplicateSuccessACKDetails other = (proto.ReplicateSuccessACK.ReplicateSuccessACKDetails) obj;

      if (getSynchronous()
          != other.getSynchronous()) return false;
      if (getAckNum()
          != other.getAckNum()) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYNCHRONOUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSynchronous());
      hash = (37 * hash) + ACKNUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAckNum());
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ReplicateSuccessACK.ReplicateSuccessACKDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ReplicateSuccessACKDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ReplicateSuccessACKDetails)
        proto.ReplicateSuccessACK.ReplicateSuccessACKDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ReplicateSuccessACK.internal_static_tutorial_ReplicateSuccessACKDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ReplicateSuccessACK.internal_static_tutorial_ReplicateSuccessACKDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.class, proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.Builder.class);
      }

      // Construct using proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        synchronous_ = false;

        ackNum_ = 0L;

        topic_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ReplicateSuccessACK.internal_static_tutorial_ReplicateSuccessACKDetails_descriptor;
      }

      @java.lang.Override
      public proto.ReplicateSuccessACK.ReplicateSuccessACKDetails getDefaultInstanceForType() {
        return proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ReplicateSuccessACK.ReplicateSuccessACKDetails build() {
        proto.ReplicateSuccessACK.ReplicateSuccessACKDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ReplicateSuccessACK.ReplicateSuccessACKDetails buildPartial() {
        proto.ReplicateSuccessACK.ReplicateSuccessACKDetails result = new proto.ReplicateSuccessACK.ReplicateSuccessACKDetails(this);
        result.synchronous_ = synchronous_;
        result.ackNum_ = ackNum_;
        result.topic_ = topic_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ReplicateSuccessACK.ReplicateSuccessACKDetails) {
          return mergeFrom((proto.ReplicateSuccessACK.ReplicateSuccessACKDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ReplicateSuccessACK.ReplicateSuccessACKDetails other) {
        if (other == proto.ReplicateSuccessACK.ReplicateSuccessACKDetails.getDefaultInstance()) return this;
        if (other.getSynchronous() != false) {
          setSynchronous(other.getSynchronous());
        }
        if (other.getAckNum() != 0L) {
          setAckNum(other.getAckNum());
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ReplicateSuccessACK.ReplicateSuccessACKDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ReplicateSuccessACK.ReplicateSuccessACKDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean synchronous_ ;
      /**
       * <code>bool synchronous = 1;</code>
       * @return The synchronous.
       */
      @java.lang.Override
      public boolean getSynchronous() {
        return synchronous_;
      }
      /**
       * <code>bool synchronous = 1;</code>
       * @param value The synchronous to set.
       * @return This builder for chaining.
       */
      public Builder setSynchronous(boolean value) {
        
        synchronous_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool synchronous = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSynchronous() {
        
        synchronous_ = false;
        onChanged();
        return this;
      }

      private long ackNum_ ;
      /**
       * <code>uint64 ackNum = 2;</code>
       * @return The ackNum.
       */
      @java.lang.Override
      public long getAckNum() {
        return ackNum_;
      }
      /**
       * <code>uint64 ackNum = 2;</code>
       * @param value The ackNum to set.
       * @return This builder for chaining.
       */
      public Builder setAckNum(long value) {
        
        ackNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ackNum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAckNum() {
        
        ackNum_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 3;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ReplicateSuccessACKDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ReplicateSuccessACKDetails)
    private static final proto.ReplicateSuccessACK.ReplicateSuccessACKDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ReplicateSuccessACK.ReplicateSuccessACKDetails();
    }

    public static proto.ReplicateSuccessACK.ReplicateSuccessACKDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplicateSuccessACKDetails>
        PARSER = new com.google.protobuf.AbstractParser<ReplicateSuccessACKDetails>() {
      @java.lang.Override
      public ReplicateSuccessACKDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplicateSuccessACKDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReplicateSuccessACKDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplicateSuccessACKDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ReplicateSuccessACK.ReplicateSuccessACKDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ReplicateSuccessACKDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ReplicateSuccessACKDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ReplicateSuccessACK.proto\022\010tutorial\"P\n" +
      "\032ReplicateSuccessACKDetails\022\023\n\013synchrono" +
      "us\030\001 \001(\010\022\016\n\006ackNum\030\002 \001(\004\022\r\n\005topic\030\003 \001(\tB" +
      "\034\n\005protoB\023ReplicateSuccessACKb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_ReplicateSuccessACKDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ReplicateSuccessACKDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ReplicateSuccessACKDetails_descriptor,
        new java.lang.String[] { "Synchronous", "AckNum", "Topic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
