// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestLeaderAndMembersInfo.proto

package proto;

public final class RequestLeaderAndMembersInfo {
  private RequestLeaderAndMembersInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestLeaderAndMembersInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.RequestLeaderAndMembersInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <code>string requestSenderType = 2;</code>
     * @return The requestSenderType.
     */
    java.lang.String getRequestSenderType();
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The bytes for requestSenderType.
     */
    com.google.protobuf.ByteString
        getRequestSenderTypeBytes();

    /**
     * <code>string requestSenderName = 3;</code>
     * @return The requestSenderName.
     */
    java.lang.String getRequestSenderName();
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The bytes for requestSenderName.
     */
    com.google.protobuf.ByteString
        getRequestSenderNameBytes();

    /**
     * <code>bool assignBrokerId = 4;</code>
     * @return The assignBrokerId.
     */
    boolean getAssignBrokerId();

    /**
     * <code>string brokerIP = 5;</code>
     * @return The brokerIP.
     */
    java.lang.String getBrokerIP();
    /**
     * <code>string brokerIP = 5;</code>
     * @return The bytes for brokerIP.
     */
    com.google.protobuf.ByteString
        getBrokerIPBytes();

    /**
     * <code>uint32 brokerPort = 6;</code>
     * @return The brokerPort.
     */
    int getBrokerPort();
  }
  /**
   * Protobuf type {@code tutorial.RequestLeaderAndMembersInfoDetails}
   */
  public static final class RequestLeaderAndMembersInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.RequestLeaderAndMembersInfoDetails)
      RequestLeaderAndMembersInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestLeaderAndMembersInfoDetails.newBuilder() to construct.
    private RequestLeaderAndMembersInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestLeaderAndMembersInfoDetails() {
      requestSenderType_ = "";
      requestSenderName_ = "";
      brokerIP_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestLeaderAndMembersInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestLeaderAndMembersInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              requestSenderType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              requestSenderName_ = s;
              break;
            }
            case 32: {

              assignBrokerId_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              brokerIP_ = s;
              break;
            }
            case 48: {

              brokerPort_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RequestLeaderAndMembersInfo.internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RequestLeaderAndMembersInfo.internal_static_tutorial_RequestLeaderAndMembersInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.class, proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }

    public static final int REQUESTSENDERTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestSenderType_;
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The requestSenderType.
     */
    @java.lang.Override
    public java.lang.String getRequestSenderType() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestSenderType_ = s;
        return s;
      }
    }
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The bytes for requestSenderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestSenderTypeBytes() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestSenderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSENDERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object requestSenderName_;
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The requestSenderName.
     */
    @java.lang.Override
    public java.lang.String getRequestSenderName() {
      java.lang.Object ref = requestSenderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestSenderName_ = s;
        return s;
      }
    }
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The bytes for requestSenderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestSenderNameBytes() {
      java.lang.Object ref = requestSenderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestSenderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSIGNBROKERID_FIELD_NUMBER = 4;
    private boolean assignBrokerId_;
    /**
     * <code>bool assignBrokerId = 4;</code>
     * @return The assignBrokerId.
     */
    @java.lang.Override
    public boolean getAssignBrokerId() {
      return assignBrokerId_;
    }

    public static final int BROKERIP_FIELD_NUMBER = 5;
    private volatile java.lang.Object brokerIP_;
    /**
     * <code>string brokerIP = 5;</code>
     * @return The brokerIP.
     */
    @java.lang.Override
    public java.lang.String getBrokerIP() {
      java.lang.Object ref = brokerIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brokerIP_ = s;
        return s;
      }
    }
    /**
     * <code>string brokerIP = 5;</code>
     * @return The bytes for brokerIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrokerIPBytes() {
      java.lang.Object ref = brokerIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROKERPORT_FIELD_NUMBER = 6;
    private int brokerPort_;
    /**
     * <code>uint32 brokerPort = 6;</code>
     * @return The brokerPort.
     */
    @java.lang.Override
    public int getBrokerPort() {
      return brokerPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestSenderType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestSenderName_);
      }
      if (assignBrokerId_ != false) {
        output.writeBool(4, assignBrokerId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brokerIP_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, brokerIP_);
      }
      if (brokerPort_ != 0) {
        output.writeUInt32(6, brokerPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestSenderType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestSenderName_);
      }
      if (assignBrokerId_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, assignBrokerId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brokerIP_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, brokerIP_);
      }
      if (brokerPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, brokerPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails)) {
        return super.equals(obj);
      }
      proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails other = (proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (!getRequestSenderType()
          .equals(other.getRequestSenderType())) return false;
      if (!getRequestSenderName()
          .equals(other.getRequestSenderName())) return false;
      if (getAssignBrokerId()
          != other.getAssignBrokerId()) return false;
      if (!getBrokerIP()
          .equals(other.getBrokerIP())) return false;
      if (getBrokerPort()
          != other.getBrokerPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + REQUESTSENDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestSenderType().hashCode();
      hash = (37 * hash) + REQUESTSENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRequestSenderName().hashCode();
      hash = (37 * hash) + ASSIGNBROKERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAssignBrokerId());
      hash = (37 * hash) + BROKERIP_FIELD_NUMBER;
      hash = (53 * hash) + getBrokerIP().hashCode();
      hash = (37 * hash) + BROKERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getBrokerPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RequestLeaderAndMembersInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.RequestLeaderAndMembersInfoDetails)
        proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RequestLeaderAndMembersInfo.internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RequestLeaderAndMembersInfo.internal_static_tutorial_RequestLeaderAndMembersInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.class, proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.Builder.class);
      }

      // Construct using proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        requestSenderType_ = "";

        requestSenderName_ = "";

        assignBrokerId_ = false;

        brokerIP_ = "";

        brokerPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RequestLeaderAndMembersInfo.internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails getDefaultInstanceForType() {
        return proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails build() {
        proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails buildPartial() {
        proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails result = new proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails(this);
        result.messageId_ = messageId_;
        result.requestSenderType_ = requestSenderType_;
        result.requestSenderName_ = requestSenderName_;
        result.assignBrokerId_ = assignBrokerId_;
        result.brokerIP_ = brokerIP_;
        result.brokerPort_ = brokerPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails) {
          return mergeFrom((proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails other) {
        if (other == proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (!other.getRequestSenderType().isEmpty()) {
          requestSenderType_ = other.requestSenderType_;
          onChanged();
        }
        if (!other.getRequestSenderName().isEmpty()) {
          requestSenderName_ = other.requestSenderName_;
          onChanged();
        }
        if (other.getAssignBrokerId() != false) {
          setAssignBrokerId(other.getAssignBrokerId());
        }
        if (!other.getBrokerIP().isEmpty()) {
          brokerIP_ = other.brokerIP_;
          onChanged();
        }
        if (other.getBrokerPort() != 0) {
          setBrokerPort(other.getBrokerPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object requestSenderType_ = "";
      /**
       * <code>string requestSenderType = 2;</code>
       * @return The requestSenderType.
       */
      public java.lang.String getRequestSenderType() {
        java.lang.Object ref = requestSenderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestSenderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @return The bytes for requestSenderType.
       */
      public com.google.protobuf.ByteString
          getRequestSenderTypeBytes() {
        java.lang.Object ref = requestSenderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestSenderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @param value The requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestSenderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSenderType() {
        
        requestSenderType_ = getDefaultInstance().getRequestSenderType();
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @param value The bytes for requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestSenderType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestSenderName_ = "";
      /**
       * <code>string requestSenderName = 3;</code>
       * @return The requestSenderName.
       */
      public java.lang.String getRequestSenderName() {
        java.lang.Object ref = requestSenderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestSenderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @return The bytes for requestSenderName.
       */
      public com.google.protobuf.ByteString
          getRequestSenderNameBytes() {
        java.lang.Object ref = requestSenderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestSenderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @param value The requestSenderName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestSenderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSenderName() {
        
        requestSenderName_ = getDefaultInstance().getRequestSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @param value The bytes for requestSenderName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestSenderName_ = value;
        onChanged();
        return this;
      }

      private boolean assignBrokerId_ ;
      /**
       * <code>bool assignBrokerId = 4;</code>
       * @return The assignBrokerId.
       */
      @java.lang.Override
      public boolean getAssignBrokerId() {
        return assignBrokerId_;
      }
      /**
       * <code>bool assignBrokerId = 4;</code>
       * @param value The assignBrokerId to set.
       * @return This builder for chaining.
       */
      public Builder setAssignBrokerId(boolean value) {
        
        assignBrokerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool assignBrokerId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssignBrokerId() {
        
        assignBrokerId_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object brokerIP_ = "";
      /**
       * <code>string brokerIP = 5;</code>
       * @return The brokerIP.
       */
      public java.lang.String getBrokerIP() {
        java.lang.Object ref = brokerIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brokerIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brokerIP = 5;</code>
       * @return The bytes for brokerIP.
       */
      public com.google.protobuf.ByteString
          getBrokerIPBytes() {
        java.lang.Object ref = brokerIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brokerIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brokerIP = 5;</code>
       * @param value The brokerIP to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brokerIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brokerIP = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerIP() {
        
        brokerIP_ = getDefaultInstance().getBrokerIP();
        onChanged();
        return this;
      }
      /**
       * <code>string brokerIP = 5;</code>
       * @param value The bytes for brokerIP to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brokerIP_ = value;
        onChanged();
        return this;
      }

      private int brokerPort_ ;
      /**
       * <code>uint32 brokerPort = 6;</code>
       * @return The brokerPort.
       */
      @java.lang.Override
      public int getBrokerPort() {
        return brokerPort_;
      }
      /**
       * <code>uint32 brokerPort = 6;</code>
       * @param value The brokerPort to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerPort(int value) {
        
        brokerPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 brokerPort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerPort() {
        
        brokerPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.RequestLeaderAndMembersInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.RequestLeaderAndMembersInfoDetails)
    private static final proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails();
    }

    public static proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestLeaderAndMembersInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<RequestLeaderAndMembersInfoDetails>() {
      @java.lang.Override
      public RequestLeaderAndMembersInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestLeaderAndMembersInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestLeaderAndMembersInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestLeaderAndMembersInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RequestLeaderAndMembersInfo.RequestLeaderAndMembersInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_RequestLeaderAndMembersInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!RequestLeaderAndMembersInfo.proto\022\010tut" +
      "orial\"\253\001\n\"RequestLeaderAndMembersInfoDet" +
      "ails\022\021\n\tmessageId\030\001 \001(\005\022\031\n\021requestSender" +
      "Type\030\002 \001(\t\022\031\n\021requestSenderName\030\003 \001(\t\022\026\n" +
      "\016assignBrokerId\030\004 \001(\010\022\020\n\010brokerIP\030\005 \001(\t\022" +
      "\022\n\nbrokerPort\030\006 \001(\rB$\n\005protoB\033RequestLea" +
      "derAndMembersInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_RequestLeaderAndMembersInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_RequestLeaderAndMembersInfoDetails_descriptor,
        new java.lang.String[] { "MessageId", "RequestSenderType", "RequestSenderName", "AssignBrokerId", "BrokerIP", "BrokerPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
