// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestLeaderInfo.proto

package proto;

public final class RequestLeaderInfo {
  private RequestLeaderInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestLeaderInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.RequestLeaderInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <code>string requestSenderType = 2;</code>
     * @return The requestSenderType.
     */
    java.lang.String getRequestSenderType();
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The bytes for requestSenderType.
     */
    com.google.protobuf.ByteString
        getRequestSenderTypeBytes();

    /**
     * <code>string requestSenderName = 3;</code>
     * @return The requestSenderName.
     */
    java.lang.String getRequestSenderName();
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The bytes for requestSenderName.
     */
    com.google.protobuf.ByteString
        getRequestSenderNameBytes();
  }
  /**
   * Protobuf type {@code tutorial.RequestLeaderInfoDetails}
   */
  public static final class RequestLeaderInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.RequestLeaderInfoDetails)
      RequestLeaderInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestLeaderInfoDetails.newBuilder() to construct.
    private RequestLeaderInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestLeaderInfoDetails() {
      requestSenderType_ = "";
      requestSenderName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestLeaderInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestLeaderInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              requestSenderType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              requestSenderName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RequestLeaderInfo.internal_static_tutorial_RequestLeaderInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RequestLeaderInfo.internal_static_tutorial_RequestLeaderInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RequestLeaderInfo.RequestLeaderInfoDetails.class, proto.RequestLeaderInfo.RequestLeaderInfoDetails.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }

    public static final int REQUESTSENDERTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestSenderType_;
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The requestSenderType.
     */
    @java.lang.Override
    public java.lang.String getRequestSenderType() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestSenderType_ = s;
        return s;
      }
    }
    /**
     * <code>string requestSenderType = 2;</code>
     * @return The bytes for requestSenderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestSenderTypeBytes() {
      java.lang.Object ref = requestSenderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestSenderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSENDERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object requestSenderName_;
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The requestSenderName.
     */
    @java.lang.Override
    public java.lang.String getRequestSenderName() {
      java.lang.Object ref = requestSenderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestSenderName_ = s;
        return s;
      }
    }
    /**
     * <code>string requestSenderName = 3;</code>
     * @return The bytes for requestSenderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestSenderNameBytes() {
      java.lang.Object ref = requestSenderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestSenderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestSenderType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestSenderName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestSenderType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestSenderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestSenderName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RequestLeaderInfo.RequestLeaderInfoDetails)) {
        return super.equals(obj);
      }
      proto.RequestLeaderInfo.RequestLeaderInfoDetails other = (proto.RequestLeaderInfo.RequestLeaderInfoDetails) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (!getRequestSenderType()
          .equals(other.getRequestSenderType())) return false;
      if (!getRequestSenderName()
          .equals(other.getRequestSenderName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + REQUESTSENDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestSenderType().hashCode();
      hash = (37 * hash) + REQUESTSENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRequestSenderName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RequestLeaderInfo.RequestLeaderInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RequestLeaderInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.RequestLeaderInfoDetails)
        proto.RequestLeaderInfo.RequestLeaderInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RequestLeaderInfo.internal_static_tutorial_RequestLeaderInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RequestLeaderInfo.internal_static_tutorial_RequestLeaderInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RequestLeaderInfo.RequestLeaderInfoDetails.class, proto.RequestLeaderInfo.RequestLeaderInfoDetails.Builder.class);
      }

      // Construct using proto.RequestLeaderInfo.RequestLeaderInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        requestSenderType_ = "";

        requestSenderName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RequestLeaderInfo.internal_static_tutorial_RequestLeaderInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.RequestLeaderInfo.RequestLeaderInfoDetails getDefaultInstanceForType() {
        return proto.RequestLeaderInfo.RequestLeaderInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RequestLeaderInfo.RequestLeaderInfoDetails build() {
        proto.RequestLeaderInfo.RequestLeaderInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RequestLeaderInfo.RequestLeaderInfoDetails buildPartial() {
        proto.RequestLeaderInfo.RequestLeaderInfoDetails result = new proto.RequestLeaderInfo.RequestLeaderInfoDetails(this);
        result.messageId_ = messageId_;
        result.requestSenderType_ = requestSenderType_;
        result.requestSenderName_ = requestSenderName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RequestLeaderInfo.RequestLeaderInfoDetails) {
          return mergeFrom((proto.RequestLeaderInfo.RequestLeaderInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RequestLeaderInfo.RequestLeaderInfoDetails other) {
        if (other == proto.RequestLeaderInfo.RequestLeaderInfoDetails.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (!other.getRequestSenderType().isEmpty()) {
          requestSenderType_ = other.requestSenderType_;
          onChanged();
        }
        if (!other.getRequestSenderName().isEmpty()) {
          requestSenderName_ = other.requestSenderName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RequestLeaderInfo.RequestLeaderInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RequestLeaderInfo.RequestLeaderInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object requestSenderType_ = "";
      /**
       * <code>string requestSenderType = 2;</code>
       * @return The requestSenderType.
       */
      public java.lang.String getRequestSenderType() {
        java.lang.Object ref = requestSenderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestSenderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @return The bytes for requestSenderType.
       */
      public com.google.protobuf.ByteString
          getRequestSenderTypeBytes() {
        java.lang.Object ref = requestSenderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestSenderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @param value The requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestSenderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSenderType() {
        
        requestSenderType_ = getDefaultInstance().getRequestSenderType();
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderType = 2;</code>
       * @param value The bytes for requestSenderType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestSenderType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestSenderName_ = "";
      /**
       * <code>string requestSenderName = 3;</code>
       * @return The requestSenderName.
       */
      public java.lang.String getRequestSenderName() {
        java.lang.Object ref = requestSenderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestSenderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @return The bytes for requestSenderName.
       */
      public com.google.protobuf.ByteString
          getRequestSenderNameBytes() {
        java.lang.Object ref = requestSenderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestSenderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @param value The requestSenderName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestSenderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSenderName() {
        
        requestSenderName_ = getDefaultInstance().getRequestSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string requestSenderName = 3;</code>
       * @param value The bytes for requestSenderName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestSenderName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.RequestLeaderInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.RequestLeaderInfoDetails)
    private static final proto.RequestLeaderInfo.RequestLeaderInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RequestLeaderInfo.RequestLeaderInfoDetails();
    }

    public static proto.RequestLeaderInfo.RequestLeaderInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestLeaderInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<RequestLeaderInfoDetails>() {
      @java.lang.Override
      public RequestLeaderInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestLeaderInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestLeaderInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestLeaderInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RequestLeaderInfo.RequestLeaderInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RequestLeaderInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_RequestLeaderInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RequestLeaderInfo.proto\022\010tutorial\"c\n\030R" +
      "equestLeaderInfoDetails\022\021\n\tmessageId\030\001 \001" +
      "(\005\022\031\n\021requestSenderType\030\002 \001(\t\022\031\n\021request" +
      "SenderName\030\003 \001(\tB\032\n\005protoB\021RequestLeader" +
      "Infob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_RequestLeaderInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_RequestLeaderInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_RequestLeaderInfoDetails_descriptor,
        new java.lang.String[] { "MessageId", "RequestSenderType", "RequestSenderName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
