// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseLeaderInfo.proto

package proto;

public final class ResponseLeaderInfo {
  private ResponseLeaderInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseLeaderAndMembersInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ResponseLeaderAndMembersInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <code>bool infoAvailable = 2;</code>
     * @return The infoAvailable.
     */
    boolean getInfoAvailable();

    /**
     * <code>uint32 leaderID = 3;</code>
     * @return The leaderID.
     */
    int getLeaderID();

    /**
     * <code>string leaderName = 4;</code>
     * @return The leaderName.
     */
    java.lang.String getLeaderName();
    /**
     * <code>string leaderName = 4;</code>
     * @return The bytes for leaderName.
     */
    com.google.protobuf.ByteString
        getLeaderNameBytes();

    /**
     * <code>string leaderIP = 5;</code>
     * @return The leaderIP.
     */
    java.lang.String getLeaderIP();
    /**
     * <code>string leaderIP = 5;</code>
     * @return The bytes for leaderIP.
     */
    com.google.protobuf.ByteString
        getLeaderIPBytes();

    /**
     * <code>int32 leaderPort = 6;</code>
     * @return The leaderPort.
     */
    int getLeaderPort();

    /**
     * <code>int32 brokerId = 7;</code>
     * @return The brokerId.
     */
    int getBrokerId();

    /**
     * <code>repeated bytes members = 8;</code>
     * @return A list containing the members.
     */
    java.util.List<com.google.protobuf.ByteString> getMembersList();
    /**
     * <code>repeated bytes members = 8;</code>
     * @return The count of members.
     */
    int getMembersCount();
    /**
     * <code>repeated bytes members = 8;</code>
     * @param index The index of the element to return.
     * @return The members at the given index.
     */
    com.google.protobuf.ByteString getMembers(int index);
  }
  /**
   * Protobuf type {@code tutorial.ResponseLeaderAndMembersInfoDetails}
   */
  public static final class ResponseLeaderAndMembersInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ResponseLeaderAndMembersInfoDetails)
      ResponseLeaderAndMembersInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseLeaderAndMembersInfoDetails.newBuilder() to construct.
    private ResponseLeaderAndMembersInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseLeaderAndMembersInfoDetails() {
      leaderName_ = "";
      leaderIP_ = "";
      members_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseLeaderAndMembersInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseLeaderAndMembersInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              infoAvailable_ = input.readBool();
              break;
            }
            case 24: {

              leaderID_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderIP_ = s;
              break;
            }
            case 48: {

              leaderPort_ = input.readInt32();
              break;
            }
            case 56: {

              brokerId_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                members_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              members_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.class, proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }

    public static final int INFOAVAILABLE_FIELD_NUMBER = 2;
    private boolean infoAvailable_;
    /**
     * <code>bool infoAvailable = 2;</code>
     * @return The infoAvailable.
     */
    @java.lang.Override
    public boolean getInfoAvailable() {
      return infoAvailable_;
    }

    public static final int LEADERID_FIELD_NUMBER = 3;
    private int leaderID_;
    /**
     * <code>uint32 leaderID = 3;</code>
     * @return The leaderID.
     */
    @java.lang.Override
    public int getLeaderID() {
      return leaderID_;
    }

    public static final int LEADERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object leaderName_;
    /**
     * <code>string leaderName = 4;</code>
     * @return The leaderName.
     */
    @java.lang.Override
    public java.lang.String getLeaderName() {
      java.lang.Object ref = leaderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderName_ = s;
        return s;
      }
    }
    /**
     * <code>string leaderName = 4;</code>
     * @return The bytes for leaderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderNameBytes() {
      java.lang.Object ref = leaderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERIP_FIELD_NUMBER = 5;
    private volatile java.lang.Object leaderIP_;
    /**
     * <code>string leaderIP = 5;</code>
     * @return The leaderIP.
     */
    @java.lang.Override
    public java.lang.String getLeaderIP() {
      java.lang.Object ref = leaderIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderIP_ = s;
        return s;
      }
    }
    /**
     * <code>string leaderIP = 5;</code>
     * @return The bytes for leaderIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderIPBytes() {
      java.lang.Object ref = leaderIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERPORT_FIELD_NUMBER = 6;
    private int leaderPort_;
    /**
     * <code>int32 leaderPort = 6;</code>
     * @return The leaderPort.
     */
    @java.lang.Override
    public int getLeaderPort() {
      return leaderPort_;
    }

    public static final int BROKERID_FIELD_NUMBER = 7;
    private int brokerId_;
    /**
     * <code>int32 brokerId = 7;</code>
     * @return The brokerId.
     */
    @java.lang.Override
    public int getBrokerId() {
      return brokerId_;
    }

    public static final int MEMBERS_FIELD_NUMBER = 8;
    private java.util.List<com.google.protobuf.ByteString> members_;
    /**
     * <code>repeated bytes members = 8;</code>
     * @return A list containing the members.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated bytes members = 8;</code>
     * @return The count of members.
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated bytes members = 8;</code>
     * @param index The index of the element to return.
     * @return The members at the given index.
     */
    public com.google.protobuf.ByteString getMembers(int index) {
      return members_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (infoAvailable_ != false) {
        output.writeBool(2, infoAvailable_);
      }
      if (leaderID_ != 0) {
        output.writeUInt32(3, leaderID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, leaderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderIP_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, leaderIP_);
      }
      if (leaderPort_ != 0) {
        output.writeInt32(6, leaderPort_);
      }
      if (brokerId_ != 0) {
        output.writeInt32(7, brokerId_);
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeBytes(8, members_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (infoAvailable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, infoAvailable_);
      }
      if (leaderID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, leaderID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, leaderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderIP_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, leaderIP_);
      }
      if (leaderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, leaderPort_);
      }
      if (brokerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, brokerId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(members_.get(i));
        }
        size += dataSize;
        size += 1 * getMembersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails)) {
        return super.equals(obj);
      }
      proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails other = (proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getInfoAvailable()
          != other.getInfoAvailable()) return false;
      if (getLeaderID()
          != other.getLeaderID()) return false;
      if (!getLeaderName()
          .equals(other.getLeaderName())) return false;
      if (!getLeaderIP()
          .equals(other.getLeaderIP())) return false;
      if (getLeaderPort()
          != other.getLeaderPort()) return false;
      if (getBrokerId()
          != other.getBrokerId()) return false;
      if (!getMembersList()
          .equals(other.getMembersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + INFOAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInfoAvailable());
      hash = (37 * hash) + LEADERID_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderID();
      hash = (37 * hash) + LEADERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderName().hashCode();
      hash = (37 * hash) + LEADERIP_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderIP().hashCode();
      hash = (37 * hash) + LEADERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderPort();
      hash = (37 * hash) + BROKERID_FIELD_NUMBER;
      hash = (53 * hash) + getBrokerId();
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ResponseLeaderAndMembersInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ResponseLeaderAndMembersInfoDetails)
        proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.class, proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.Builder.class);
      }

      // Construct using proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        infoAvailable_ = false;

        leaderID_ = 0;

        leaderName_ = "";

        leaderIP_ = "";

        leaderPort_ = 0;

        brokerId_ = 0;

        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails getDefaultInstanceForType() {
        return proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails build() {
        proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails buildPartial() {
        proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails result = new proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails(this);
        int from_bitField0_ = bitField0_;
        result.messageId_ = messageId_;
        result.infoAvailable_ = infoAvailable_;
        result.leaderID_ = leaderID_;
        result.leaderName_ = leaderName_;
        result.leaderIP_ = leaderIP_;
        result.leaderPort_ = leaderPort_;
        result.brokerId_ = brokerId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.members_ = members_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails) {
          return mergeFrom((proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails other) {
        if (other == proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getInfoAvailable() != false) {
          setInfoAvailable(other.getInfoAvailable());
        }
        if (other.getLeaderID() != 0) {
          setLeaderID(other.getLeaderID());
        }
        if (!other.getLeaderName().isEmpty()) {
          leaderName_ = other.leaderName_;
          onChanged();
        }
        if (!other.getLeaderIP().isEmpty()) {
          leaderIP_ = other.leaderIP_;
          onChanged();
        }
        if (other.getLeaderPort() != 0) {
          setLeaderPort(other.getLeaderPort());
        }
        if (other.getBrokerId() != 0) {
          setBrokerId(other.getBrokerId());
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private boolean infoAvailable_ ;
      /**
       * <code>bool infoAvailable = 2;</code>
       * @return The infoAvailable.
       */
      @java.lang.Override
      public boolean getInfoAvailable() {
        return infoAvailable_;
      }
      /**
       * <code>bool infoAvailable = 2;</code>
       * @param value The infoAvailable to set.
       * @return This builder for chaining.
       */
      public Builder setInfoAvailable(boolean value) {
        
        infoAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool infoAvailable = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfoAvailable() {
        
        infoAvailable_ = false;
        onChanged();
        return this;
      }

      private int leaderID_ ;
      /**
       * <code>uint32 leaderID = 3;</code>
       * @return The leaderID.
       */
      @java.lang.Override
      public int getLeaderID() {
        return leaderID_;
      }
      /**
       * <code>uint32 leaderID = 3;</code>
       * @param value The leaderID to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderID(int value) {
        
        leaderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 leaderID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderID() {
        
        leaderID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leaderName_ = "";
      /**
       * <code>string leaderName = 4;</code>
       * @return The leaderName.
       */
      public java.lang.String getLeaderName() {
        java.lang.Object ref = leaderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leaderName = 4;</code>
       * @return The bytes for leaderName.
       */
      public com.google.protobuf.ByteString
          getLeaderNameBytes() {
        java.lang.Object ref = leaderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leaderName = 4;</code>
       * @param value The leaderName to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leaderName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderName() {
        
        leaderName_ = getDefaultInstance().getLeaderName();
        onChanged();
        return this;
      }
      /**
       * <code>string leaderName = 4;</code>
       * @param value The bytes for leaderName to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object leaderIP_ = "";
      /**
       * <code>string leaderIP = 5;</code>
       * @return The leaderIP.
       */
      public java.lang.String getLeaderIP() {
        java.lang.Object ref = leaderIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leaderIP = 5;</code>
       * @return The bytes for leaderIP.
       */
      public com.google.protobuf.ByteString
          getLeaderIPBytes() {
        java.lang.Object ref = leaderIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leaderIP = 5;</code>
       * @param value The leaderIP to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leaderIP = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderIP() {
        
        leaderIP_ = getDefaultInstance().getLeaderIP();
        onChanged();
        return this;
      }
      /**
       * <code>string leaderIP = 5;</code>
       * @param value The bytes for leaderIP to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderIP_ = value;
        onChanged();
        return this;
      }

      private int leaderPort_ ;
      /**
       * <code>int32 leaderPort = 6;</code>
       * @return The leaderPort.
       */
      @java.lang.Override
      public int getLeaderPort() {
        return leaderPort_;
      }
      /**
       * <code>int32 leaderPort = 6;</code>
       * @param value The leaderPort to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderPort(int value) {
        
        leaderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaderPort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderPort() {
        
        leaderPort_ = 0;
        onChanged();
        return this;
      }

      private int brokerId_ ;
      /**
       * <code>int32 brokerId = 7;</code>
       * @return The brokerId.
       */
      @java.lang.Override
      public int getBrokerId() {
        return brokerId_;
      }
      /**
       * <code>int32 brokerId = 7;</code>
       * @param value The brokerId to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerId(int value) {
        
        brokerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 brokerId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerId() {
        
        brokerId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> members_ = java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          members_ = new java.util.ArrayList<com.google.protobuf.ByteString>(members_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @return A list containing the members.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getMembersList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(members_) : members_;
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @return The count of members.
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @param index The index of the element to return.
       * @return The members at the given index.
       */
      public com.google.protobuf.ByteString getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @param index The index to set the value at.
       * @param value The members to set.
       * @return This builder for chaining.
       */
      public Builder setMembers(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @param value The members to add.
       * @return This builder for chaining.
       */
      public Builder addMembers(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @param values The members to add.
       * @return This builder for chaining.
       */
      public Builder addAllMembers(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes members = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMembers() {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ResponseLeaderAndMembersInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ResponseLeaderAndMembersInfoDetails)
    private static final proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails();
    }

    public static proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseLeaderAndMembersInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<ResponseLeaderAndMembersInfoDetails>() {
      @java.lang.Override
      public ResponseLeaderAndMembersInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseLeaderAndMembersInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseLeaderAndMembersInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseLeaderAndMembersInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ResponseLeaderInfo.ResponseLeaderAndMembersInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ResponseLeaderInfo.proto\022\010tutorial\"\276\001\n" +
      "#ResponseLeaderAndMembersInfoDetails\022\021\n\t" +
      "messageId\030\001 \001(\005\022\025\n\rinfoAvailable\030\002 \001(\010\022\020" +
      "\n\010leaderID\030\003 \001(\r\022\022\n\nleaderName\030\004 \001(\t\022\020\n\010" +
      "leaderIP\030\005 \001(\t\022\022\n\nleaderPort\030\006 \001(\005\022\020\n\010br" +
      "okerId\030\007 \001(\005\022\017\n\007members\030\010 \003(\014B\033\n\005protoB\022" +
      "ResponseLeaderInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ResponseLeaderAndMembersInfoDetails_descriptor,
        new java.lang.String[] { "MessageId", "InfoAvailable", "LeaderID", "LeaderName", "LeaderIP", "LeaderPort", "BrokerId", "Members", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
