// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseLeaderInfo.proto

package proto;

public final class ResponseLeaderInfo {
  private ResponseLeaderInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseLeaderInfoDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ResponseLeaderInfoDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <code>string leaderName = 2;</code>
     * @return The leaderName.
     */
    java.lang.String getLeaderName();
    /**
     * <code>string leaderName = 2;</code>
     * @return The bytes for leaderName.
     */
    com.google.protobuf.ByteString
        getLeaderNameBytes();

    /**
     * <code>string leaderIP = 3;</code>
     * @return The leaderIP.
     */
    java.lang.String getLeaderIP();
    /**
     * <code>string leaderIP = 3;</code>
     * @return The bytes for leaderIP.
     */
    com.google.protobuf.ByteString
        getLeaderIPBytes();

    /**
     * <code>int32 leaderPort = 4;</code>
     * @return The leaderPort.
     */
    int getLeaderPort();
  }
  /**
   * Protobuf type {@code tutorial.ResponseLeaderInfoDetails}
   */
  public static final class ResponseLeaderInfoDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ResponseLeaderInfoDetails)
      ResponseLeaderInfoDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseLeaderInfoDetails.newBuilder() to construct.
    private ResponseLeaderInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseLeaderInfoDetails() {
      leaderName_ = "";
      leaderIP_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseLeaderInfoDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseLeaderInfoDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderIP_ = s;
              break;
            }
            case 32: {

              leaderPort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.class, proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }

    public static final int LEADERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object leaderName_;
    /**
     * <code>string leaderName = 2;</code>
     * @return The leaderName.
     */
    @java.lang.Override
    public java.lang.String getLeaderName() {
      java.lang.Object ref = leaderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderName_ = s;
        return s;
      }
    }
    /**
     * <code>string leaderName = 2;</code>
     * @return The bytes for leaderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderNameBytes() {
      java.lang.Object ref = leaderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERIP_FIELD_NUMBER = 3;
    private volatile java.lang.Object leaderIP_;
    /**
     * <code>string leaderIP = 3;</code>
     * @return The leaderIP.
     */
    @java.lang.Override
    public java.lang.String getLeaderIP() {
      java.lang.Object ref = leaderIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderIP_ = s;
        return s;
      }
    }
    /**
     * <code>string leaderIP = 3;</code>
     * @return The bytes for leaderIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderIPBytes() {
      java.lang.Object ref = leaderIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERPORT_FIELD_NUMBER = 4;
    private int leaderPort_;
    /**
     * <code>int32 leaderPort = 4;</code>
     * @return The leaderPort.
     */
    @java.lang.Override
    public int getLeaderPort() {
      return leaderPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderIP_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, leaderIP_);
      }
      if (leaderPort_ != 0) {
        output.writeInt32(4, leaderPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderIP_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, leaderIP_);
      }
      if (leaderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leaderPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ResponseLeaderInfo.ResponseLeaderInfoDetails)) {
        return super.equals(obj);
      }
      proto.ResponseLeaderInfo.ResponseLeaderInfoDetails other = (proto.ResponseLeaderInfo.ResponseLeaderInfoDetails) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (!getLeaderName()
          .equals(other.getLeaderName())) return false;
      if (!getLeaderIP()
          .equals(other.getLeaderIP())) return false;
      if (getLeaderPort()
          != other.getLeaderPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + LEADERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderName().hashCode();
      hash = (37 * hash) + LEADERIP_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderIP().hashCode();
      hash = (37 * hash) + LEADERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ResponseLeaderInfo.ResponseLeaderInfoDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ResponseLeaderInfoDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ResponseLeaderInfoDetails)
        proto.ResponseLeaderInfo.ResponseLeaderInfoDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderInfoDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderInfoDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.class, proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.Builder.class);
      }

      // Construct using proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        leaderName_ = "";

        leaderIP_ = "";

        leaderPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ResponseLeaderInfo.internal_static_tutorial_ResponseLeaderInfoDetails_descriptor;
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderInfoDetails getDefaultInstanceForType() {
        return proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderInfoDetails build() {
        proto.ResponseLeaderInfo.ResponseLeaderInfoDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ResponseLeaderInfo.ResponseLeaderInfoDetails buildPartial() {
        proto.ResponseLeaderInfo.ResponseLeaderInfoDetails result = new proto.ResponseLeaderInfo.ResponseLeaderInfoDetails(this);
        result.messageId_ = messageId_;
        result.leaderName_ = leaderName_;
        result.leaderIP_ = leaderIP_;
        result.leaderPort_ = leaderPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ResponseLeaderInfo.ResponseLeaderInfoDetails) {
          return mergeFrom((proto.ResponseLeaderInfo.ResponseLeaderInfoDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ResponseLeaderInfo.ResponseLeaderInfoDetails other) {
        if (other == proto.ResponseLeaderInfo.ResponseLeaderInfoDetails.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (!other.getLeaderName().isEmpty()) {
          leaderName_ = other.leaderName_;
          onChanged();
        }
        if (!other.getLeaderIP().isEmpty()) {
          leaderIP_ = other.leaderIP_;
          onChanged();
        }
        if (other.getLeaderPort() != 0) {
          setLeaderPort(other.getLeaderPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ResponseLeaderInfo.ResponseLeaderInfoDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ResponseLeaderInfo.ResponseLeaderInfoDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leaderName_ = "";
      /**
       * <code>string leaderName = 2;</code>
       * @return The leaderName.
       */
      public java.lang.String getLeaderName() {
        java.lang.Object ref = leaderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leaderName = 2;</code>
       * @return The bytes for leaderName.
       */
      public com.google.protobuf.ByteString
          getLeaderNameBytes() {
        java.lang.Object ref = leaderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leaderName = 2;</code>
       * @param value The leaderName to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leaderName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderName() {
        
        leaderName_ = getDefaultInstance().getLeaderName();
        onChanged();
        return this;
      }
      /**
       * <code>string leaderName = 2;</code>
       * @param value The bytes for leaderName to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object leaderIP_ = "";
      /**
       * <code>string leaderIP = 3;</code>
       * @return The leaderIP.
       */
      public java.lang.String getLeaderIP() {
        java.lang.Object ref = leaderIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leaderIP = 3;</code>
       * @return The bytes for leaderIP.
       */
      public com.google.protobuf.ByteString
          getLeaderIPBytes() {
        java.lang.Object ref = leaderIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leaderIP = 3;</code>
       * @param value The leaderIP to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leaderIP = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderIP() {
        
        leaderIP_ = getDefaultInstance().getLeaderIP();
        onChanged();
        return this;
      }
      /**
       * <code>string leaderIP = 3;</code>
       * @param value The bytes for leaderIP to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderIP_ = value;
        onChanged();
        return this;
      }

      private int leaderPort_ ;
      /**
       * <code>int32 leaderPort = 4;</code>
       * @return The leaderPort.
       */
      @java.lang.Override
      public int getLeaderPort() {
        return leaderPort_;
      }
      /**
       * <code>int32 leaderPort = 4;</code>
       * @param value The leaderPort to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderPort(int value) {
        
        leaderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaderPort = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderPort() {
        
        leaderPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ResponseLeaderInfoDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ResponseLeaderInfoDetails)
    private static final proto.ResponseLeaderInfo.ResponseLeaderInfoDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ResponseLeaderInfo.ResponseLeaderInfoDetails();
    }

    public static proto.ResponseLeaderInfo.ResponseLeaderInfoDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseLeaderInfoDetails>
        PARSER = new com.google.protobuf.AbstractParser<ResponseLeaderInfoDetails>() {
      @java.lang.Override
      public ResponseLeaderInfoDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseLeaderInfoDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseLeaderInfoDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseLeaderInfoDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ResponseLeaderInfo.ResponseLeaderInfoDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ResponseLeaderInfoDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ResponseLeaderInfoDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ResponseLeaderInfo.proto\022\010tutorial\"h\n\031" +
      "ResponseLeaderInfoDetails\022\021\n\tmessageId\030\001" +
      " \001(\005\022\022\n\nleaderName\030\002 \001(\t\022\020\n\010leaderIP\030\003 \001" +
      "(\t\022\022\n\nleaderPort\030\004 \001(\005B\033\n\005protoB\022Respons" +
      "eLeaderInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_ResponseLeaderInfoDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ResponseLeaderInfoDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ResponseLeaderInfoDetails_descriptor,
        new java.lang.String[] { "MessageId", "LeaderName", "LeaderIP", "LeaderPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
