// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartSyncUpMessage.proto

package proto;

public final class StartSyncUpMessage {
  private StartSyncUpMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StartSyncUpMessageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.StartSyncUpMessageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 memberId = 1;</code>
     * @return The memberId.
     */
    int getMemberId();

    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @return A list containing the topicSnapshot.
     */
    java.util.List<com.google.protobuf.ByteString> getTopicSnapshotList();
    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @return The count of topicSnapshot.
     */
    int getTopicSnapshotCount();
    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @param index The index of the element to return.
     * @return The topicSnapshot at the given index.
     */
    com.google.protobuf.ByteString getTopicSnapshot(int index);
  }
  /**
   * Protobuf type {@code tutorial.StartSyncUpMessageDetails}
   */
  public static final class StartSyncUpMessageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.StartSyncUpMessageDetails)
      StartSyncUpMessageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StartSyncUpMessageDetails.newBuilder() to construct.
    private StartSyncUpMessageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StartSyncUpMessageDetails() {
      topicSnapshot_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StartSyncUpMessageDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StartSyncUpMessageDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              memberId_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                topicSnapshot_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              topicSnapshot_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          topicSnapshot_ = java.util.Collections.unmodifiableList(topicSnapshot_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.StartSyncUpMessage.internal_static_tutorial_StartSyncUpMessageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.StartSyncUpMessage.internal_static_tutorial_StartSyncUpMessageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.StartSyncUpMessage.StartSyncUpMessageDetails.class, proto.StartSyncUpMessage.StartSyncUpMessageDetails.Builder.class);
    }

    public static final int MEMBERID_FIELD_NUMBER = 1;
    private int memberId_;
    /**
     * <code>uint32 memberId = 1;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public int getMemberId() {
      return memberId_;
    }

    public static final int TOPICSNAPSHOT_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> topicSnapshot_;
    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @return A list containing the topicSnapshot.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getTopicSnapshotList() {
      return topicSnapshot_;
    }
    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @return The count of topicSnapshot.
     */
    public int getTopicSnapshotCount() {
      return topicSnapshot_.size();
    }
    /**
     * <code>repeated bytes topicSnapshot = 2;</code>
     * @param index The index of the element to return.
     * @return The topicSnapshot at the given index.
     */
    public com.google.protobuf.ByteString getTopicSnapshot(int index) {
      return topicSnapshot_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (memberId_ != 0) {
        output.writeUInt32(1, memberId_);
      }
      for (int i = 0; i < topicSnapshot_.size(); i++) {
        output.writeBytes(2, topicSnapshot_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (memberId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, memberId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < topicSnapshot_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(topicSnapshot_.get(i));
        }
        size += dataSize;
        size += 1 * getTopicSnapshotList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.StartSyncUpMessage.StartSyncUpMessageDetails)) {
        return super.equals(obj);
      }
      proto.StartSyncUpMessage.StartSyncUpMessageDetails other = (proto.StartSyncUpMessage.StartSyncUpMessageDetails) obj;

      if (getMemberId()
          != other.getMemberId()) return false;
      if (!getTopicSnapshotList()
          .equals(other.getTopicSnapshotList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + getMemberId();
      if (getTopicSnapshotCount() > 0) {
        hash = (37 * hash) + TOPICSNAPSHOT_FIELD_NUMBER;
        hash = (53 * hash) + getTopicSnapshotList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.StartSyncUpMessage.StartSyncUpMessageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.StartSyncUpMessageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.StartSyncUpMessageDetails)
        proto.StartSyncUpMessage.StartSyncUpMessageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.StartSyncUpMessage.internal_static_tutorial_StartSyncUpMessageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.StartSyncUpMessage.internal_static_tutorial_StartSyncUpMessageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.StartSyncUpMessage.StartSyncUpMessageDetails.class, proto.StartSyncUpMessage.StartSyncUpMessageDetails.Builder.class);
      }

      // Construct using proto.StartSyncUpMessage.StartSyncUpMessageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        memberId_ = 0;

        topicSnapshot_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.StartSyncUpMessage.internal_static_tutorial_StartSyncUpMessageDetails_descriptor;
      }

      @java.lang.Override
      public proto.StartSyncUpMessage.StartSyncUpMessageDetails getDefaultInstanceForType() {
        return proto.StartSyncUpMessage.StartSyncUpMessageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.StartSyncUpMessage.StartSyncUpMessageDetails build() {
        proto.StartSyncUpMessage.StartSyncUpMessageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.StartSyncUpMessage.StartSyncUpMessageDetails buildPartial() {
        proto.StartSyncUpMessage.StartSyncUpMessageDetails result = new proto.StartSyncUpMessage.StartSyncUpMessageDetails(this);
        int from_bitField0_ = bitField0_;
        result.memberId_ = memberId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          topicSnapshot_ = java.util.Collections.unmodifiableList(topicSnapshot_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.topicSnapshot_ = topicSnapshot_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.StartSyncUpMessage.StartSyncUpMessageDetails) {
          return mergeFrom((proto.StartSyncUpMessage.StartSyncUpMessageDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.StartSyncUpMessage.StartSyncUpMessageDetails other) {
        if (other == proto.StartSyncUpMessage.StartSyncUpMessageDetails.getDefaultInstance()) return this;
        if (other.getMemberId() != 0) {
          setMemberId(other.getMemberId());
        }
        if (!other.topicSnapshot_.isEmpty()) {
          if (topicSnapshot_.isEmpty()) {
            topicSnapshot_ = other.topicSnapshot_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTopicSnapshotIsMutable();
            topicSnapshot_.addAll(other.topicSnapshot_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.StartSyncUpMessage.StartSyncUpMessageDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.StartSyncUpMessage.StartSyncUpMessageDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int memberId_ ;
      /**
       * <code>uint32 memberId = 1;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public int getMemberId() {
        return memberId_;
      }
      /**
       * <code>uint32 memberId = 1;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(int value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 memberId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        
        memberId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> topicSnapshot_ = java.util.Collections.emptyList();
      private void ensureTopicSnapshotIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          topicSnapshot_ = new java.util.ArrayList<com.google.protobuf.ByteString>(topicSnapshot_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @return A list containing the topicSnapshot.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTopicSnapshotList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(topicSnapshot_) : topicSnapshot_;
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @return The count of topicSnapshot.
       */
      public int getTopicSnapshotCount() {
        return topicSnapshot_.size();
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @param index The index of the element to return.
       * @return The topicSnapshot at the given index.
       */
      public com.google.protobuf.ByteString getTopicSnapshot(int index) {
        return topicSnapshot_.get(index);
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @param index The index to set the value at.
       * @param value The topicSnapshot to set.
       * @return This builder for chaining.
       */
      public Builder setTopicSnapshot(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicSnapshotIsMutable();
        topicSnapshot_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @param value The topicSnapshot to add.
       * @return This builder for chaining.
       */
      public Builder addTopicSnapshot(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicSnapshotIsMutable();
        topicSnapshot_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @param values The topicSnapshot to add.
       * @return This builder for chaining.
       */
      public Builder addAllTopicSnapshot(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTopicSnapshotIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, topicSnapshot_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topicSnapshot = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopicSnapshot() {
        topicSnapshot_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.StartSyncUpMessageDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.StartSyncUpMessageDetails)
    private static final proto.StartSyncUpMessage.StartSyncUpMessageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.StartSyncUpMessage.StartSyncUpMessageDetails();
    }

    public static proto.StartSyncUpMessage.StartSyncUpMessageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StartSyncUpMessageDetails>
        PARSER = new com.google.protobuf.AbstractParser<StartSyncUpMessageDetails>() {
      @java.lang.Override
      public StartSyncUpMessageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StartSyncUpMessageDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StartSyncUpMessageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StartSyncUpMessageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.StartSyncUpMessage.StartSyncUpMessageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_StartSyncUpMessageDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_StartSyncUpMessageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030StartSyncUpMessage.proto\022\010tutorial\"D\n\031" +
      "StartSyncUpMessageDetails\022\020\n\010memberId\030\001 " +
      "\001(\r\022\025\n\rtopicSnapshot\030\002 \003(\014B\033\n\005protoB\022Sta" +
      "rtSyncUpMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_StartSyncUpMessageDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_StartSyncUpMessageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_StartSyncUpMessageDetails_descriptor,
        new java.lang.String[] { "MemberId", "TopicSnapshot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
